apiVersion: apps/v1
kind: Deployment
metadata:
  name: codestate
  labels:
    app: codestateconverter
    version: v2
spec:
  selector:
    matchLabels:
      app: codestateconverter
  replicas: 1
  template:
    metadata:
      labels:
        app: codestateconverter
    spec:
      containers:
        - name: codestate
          image:  gcr.io/anthos-poc-252613/codestate:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: codestate
spec:
  selector:
    app: codestateconverter
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
